name: simple-build
on: [push]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: submodules
        run: |
          git config --global url."https://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:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          git submodule update --init --recursive
      - name: install-deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libfreetype-dev libglew-dev libglfw3-dev libogg-dev libopenal-dev libpng-dev libvorbis-dev zlib1g-dev
      - name: configure
        run: |
          cd ${{ github.workspace }}
          ./configure.sh
      - name: build
        run: |
          cd ${{ github.workspace }}
          ./build.sh